version: "3.5"
services:
  postgres:
    image: postgres
    container_name: postgres-keycloak
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - type: "volume"
        source: keycloak-flask-db-data
        target: /var/lib/postgresql/data
  keycloak:
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:11.0.0
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_ADDR: postgres
    volumes:
      - type: "volume"
        source: keycloak-flask-data
        target: /opt/jboss/keycloak/standalone/data
  flask-app:
    image: akring1729/flask-app:0.1
    container_name: flask-app
    ports:
      - 5000:5000
volumes:
  keycloak-flask-db-data:
  keycloak-flask-data:
